### ISSUE TITLE
Conflicting indexes were encountered when renaming coordinate dimensions.

### ISSUE THREAD

**Issue by Anatomical** [GISWLH/plot-function#1]
Thank you for your contribution to this project. I have noticed an error in your code and I would like to kindly bring it to your attention.
When I ran the notebook with **xarray version 2022.11.0**, there was an error with conflicting indexes. The problem code is in **line 8 of the second block** of plotbook.ipynb.
```
ds.coords['lat'] = ('lat', `lat.to_numpy())
----> ds.coords['lon'] = ('lon', lon.to_numpy())  # Error reported here
ds = ds.reset_coords(names=['latitude','longitude'], drop=True) 
```
Error details are as follows
```
ValueError: cannot re-index or align objects with conflicting indexes found for the following dimensions: 'lat' (2 conflicting indexes)
Conflicting indexes may occur when
- they relate to different sets of coordinate and/or dimension names
- they don't have the same type
- they may be used to reindex data along common dimensions
```
When I try to change `ds = ds.rename_dims ({'latitude':'lat','longitude':'lon'})` to `ds = ds.swap_dims({'latitude':'lat','longitude':'lon'})`, then the error is resolved.
Perhaps this error needs to be fixed in the project, this is just my personal opinion and for reference only.

**Comment by GISWLH** [comment]
Thank you! you are right. I admire your effort to enhance the code, if other reader have same problems, they can change ``ds = ds.rename_dims ({'latitude':'lat','longitude':'lon'})`` to ``ds = ds.swap_dims({'latitude':'lat','longitude':'lon'})``
